### ISSUE TITLE
压缩图片是执行那个

### ISSUE THREAD

**Issue by zoujianliang1994** [cj1128/oimg#1]

**Comment by cj1128** [comment]
@zoujianliang1994 直接执行指令就是压缩图片，例如 `oimg file1.jpg`。

**Comment by zoujianliang1994** [comment]
我最开始是执行这个的yarn global add oimg，然后执行oimg images/test.jpg，报错没有columnify这个模块，现在我把这个屏蔽了就可以了。多谢大佬的教程

**Comment by cj1128** [comment]
@zoujianliang1994 我看了一下，是我的 `package.json` 文件里面漏了 `columnify` 模块，抱歉，我更新了 package，再次安装就可以了。

BTW: `columnify` 这个包用于格式化输出。
